name: Tweet Movie Frames

on:
  schedule:     #runs 18 times every day
    # This workflow runs every 90 minutes (18 times every day)
    - cron: '0 */3 * * *'  # At minute 0 past every 3rd hour (e.g., 00:00, 03:00, 06:00, etc.)
    - cron: '30 1/3 * * *' # At minute 30 past every 3rd hour, starting at hour 1 (e.g., 01:30, 04:30, 07:30, etc.) 

  workflow_dispatch:  # Manual trigger

jobs:
  tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy python-dotenv

      - name: Run tweet script
        run: python main.py
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add "last frame tweeted.txt"
          git commit -m "Update last frame tweeted" || exit 0
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}